from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('register',views.register,name='reg'),
    path('navigate/',views.disp_det,name='details'),
    path('student_login/',views.student_login,name='student_login'),
    path('teacher_login/',views.teacher_login,name='teacher_login'),
    path('admin_login/',views.admin_login,name='admin_login'),
    path('admin_login_check/',views.admin_check,name='admin_check'),
    path('admin_login/dash_board/',views.admin_dashboard,name='admin_dashboard'),
    path('admin_login/dash_board/admin_student/',views.add_student,name='add_student'),
    path('admin_login/dash_board/admin_del_student/',views.del_student,name='del_student'),
    path('admin_login/dash_board/admin_course_student/',views.add_teacher_course_student,name='add_teacher_course_student'),
    path('admin_login/dash_board/del_admin_course_student/',views.del_teacher_course_student,name='del_teacher_course_student'),
    path('admin_login/dash_board/',views.admin_dashboard,name='admin_dashboard'),
    path('admin_login/dash_board/admin_student/',views.add_student,name='add_student'),
    path('admin_login/dash_board/add_teacher/',views.add_teacher,name='add_teacher'),
    path('admin_login/dash_board/add_course/',views.add_course,name='add_course'),
    path('admin_login/dash_board/add_department/',views.add_department,name='add_department'),
    path('student_login/student_dashboard/',views.student_dashboard,name='student_dashboard'),
    path('student_login/student_dashboard/student_check',views.student_check,name ='student_check'),
    path('student_login/student_dashboard/profile/',views.view_student_profile,name='view_student_profile'),
    path('student_login/student_dashboard/todays_lectures/',views.students_todays_lectures,name='students_todays_lectures'),
    path('student_login/student_dashboard/mark_attendance/',views.mark_attendance,name='mark_attendance'),
    path('student_login/student_dashboard/mark_attendance/give_attendance/',views.give_attendance,name='give_attendance'),
    path('student_login/student_dashboard/mark_attendance/give_attendance/add_attendance',views.add_attendance,name='add_attendance'),
    path('student_login/student_dashboard/view_my_attendance/',views.view_my_attendance,name='view_my_attendance'),
    path('teacher_login/teacher_dashboard',views.teacher_dashboard,name='teacher_dashboard'),
    path('teacher_login/teacher_dashboard/teacher_check',views.teacher_check,name='teacher_check'),
    path('teacher_login/teacher_dashboard/my_profile',views.teacher_profile,name='teacher_profile'),
    path('teacher_login/teacher_dashboard/my_courses',views.teacher_courses,name='teacher_courses'),
    path('teacher_login/teacher_dashboard/my_courses/add_lecture',views.add_lecture,name='add_lecture'),
    path('teacher_login/teacher_dashboard/my_courses/delete_lecture',views.delete_lecture,name='delete_lecture'),
    path('teacher_login/teacher_dashboard/my_courses/update_lecture',views.update_lecture,name='update_lecture'),
    path('teacher_login/teacher_dashboard/my_lectures',views.teacher_lectures,name='teacher_lectures'),
    path('teacher_login/teacher_dashboard/student_attendance_details',views.student_attendance_details,name='student_attendance_details'),
    path('teacher_login/teacher_dashboard/insert_lecture',views.insert_lecture,name='insert_lecture'),
    path('teacher_login/teacher_dashboard/delete_existing_lecture',views.delete_existing_lecture,name='delete_existing_lecture'),
    path('teacher_login/teacher_dashboard/update_existing_lecture',views.update_existing_lecture,name='update_existing_lecture'),
]